image: node:latest

variables:
  CI: 'true'

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

stages:
  - test 
  - build

lint:
  stage: test 
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test 

build:
  stage: build
  script:
    - yarn build
  artifacts:
    expire_in: '1 week'
    paths:
      - public/
