language: node_js

services: docker

node_js:
  - "node"

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

jobs:
  include:
    - stage: test
      script: npm run lint
    - # stage name omitted, since it remains the same
      script: npm test
    - stage: deploy
      script: npm run build
