language: node_js

cache:
  - node_modules/

services: docker

node_js:
  - "node"

jobs:
  include:
    - stage: test 
      script: npm run lint
    - # stage name omitted since it remains the same
      script: npm test
