language: node_js

services: docker

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules/

jobs:
  include:
    - stage: test
      script: yarn lint
    - # stage name omitted, since it remains the same
      script: yarn test
    - stage: build 
      script: yarn build
