siteTitle = "Nicholas Young"
siteDescr = "Perspectives on family and industry; from a husband, father, and media entrepreneur."
siteAuthor = "Nicholas Young"
siteTwitterUrl = "https://twitter.com/nicholaswyoung"
googleAnalyticsId = "UA-33160485-1"
linkPrefix = "/"
